### ISSUE TITLE
Invalid Form Key. Please refresh the page

### ISSUE THREAD

**Issue by ghost** [cloudipsp/magento2#2]
When I paid order and go back to the shop I see error "Invalid Form Key. Please refresh the page" on home page
I use magento v2.3

**Comment by has-well** [comment]
Hello, in merchant portal go to technical settings and choose "Redirect method to the result page" to GET_WITHOUT_PARAMETERS
![image](https://user-images.githubusercontent.com/14124011/72543449-6937d680-388e-11ea-892e-5e5a00b5a0e5.png)
